
CREATE DATABASE ObligatorioP3

use ObligatorioP3

CREATE TABLE USUARIO(EMAIL VARCHAR(20) primary key  not null,
                     PWD VARCHAR(10))
 
 CREATE TABLE PERSONA(NOMBRE VARCHAR(20),
                      APELLIDO VARCHAR(20),
					   PAIS VARCHAR(20),
					   NOM_ARTISTICO VARCHAR(20),
					   NUM_REGISTRO INT PRIMARY KEY NOT NULL)


CREATE TABLE MATERIAL(CODIGO VARCHAR(20) PRIMARY KEY NOT NULL,
					TITULO VARCHAR(20) ,
					AÑO INT,
					DESCRIPCION VARCHAR(50),
					IMAGEN VARCHAR(50),
					ENTRADAS INT,
					MONTO DECIMAL(10,5),
					DURACION INT)


CREATE TABLE TEMPORADA(TITULO VARCHAR(20)NOT NULL,
						NUMERO INT,
						FECHA DATETIME,
						IMAGEN VARCHAR(50),
						CODIGO_MATERIAL VARCHAR(20)NOT NULL,
						PRIMARY KEY(TITULO,CODIGO_MATERIAL))


CREATE TABLE EPISODIO(ORDINAL INT,
					  TITULO VARCHAR(20),
					  DESCRIPCION VARCHAR(50),
						DURACION INT,
						TEMPORADA VARCHAR(20)NOT NULL,
						CODIGO_MATERIAL VARCHAR(20) NOT NULL,
						PRIMARY KEY(TEMPORADA,CODIGO_MATERIAL))


 CREATE TABLE ACTORES(CODIGO_MATERIAL VARCHAR(20),
                      NUM_REGISTRO INT,
					  PARTICIPACION INT
					  PRIMARY KEY(CODIGO_MATERIAL,NUM_REGISTRO))


CREATE TABLE DIRECTORES(CODIGO_MATERIAL VARCHAR(20),
                      NUM_REGISTRO INT,
					  PRIMARY KEY(CODIGO_MATERIAL,NUM_REGISTRO))					                   



